/*============================================
PROYECTO: Sistema de control de asistencias
BD: Oracle
AUTOR: Luis Carbajal
FECHA: 06/12/2025
=============================================*/
--Tabla de Roles
CREATE TABLE ROL( id_rol NUMBER(2)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  nombre VARCHAR(25) NOT NULL UNIQUE 
);

COMMENT ON TABLE ROL IS 'Tabla maestra, que define los niveles de acceso y permiso dentro del sistema.';
--------------------------------------------------------------------------------------------------------------
--TABLA DE USUARIOS
CREATE TABLE USUARIO( id_usuario      NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                      username        VARCHAR(50)   NOT NULL UNIQUE                              ,
                      clave_hash      VARCHAR2(100) NOT NULL                                     ,
                      nombre_completo VARCHAR2(100) NOT NULL                                     ,
                      email           VARCHAR2(100)                                              ,
                      id_rol          NUMBER(2)     NOT NULL                                     ,
                      estado          NUMBER(1)     DEFAULT 1 NOT NULL CHECK(estado IN (0,1))    ,--1=Activo, 0=Inactivo
                      CONSTRAINT fk_user_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);
COMMENT ON TABLE USUARIO IS '1:Activo, 0:Inactivo';
---------------------------------------------------------------------------------------------------------------
--TABLA DE PARAMETROS
CREATE TABLE tbl_calendario_laboral(fec_calendario DATE PRIMARY KEY,
                                    tipo           VARCHAR(20) NOT NULL,
                                    descripcion    VARCHAR2(100)
)

----------------------------------------------------------------------------------------------------------------
--TABLA DE CALENDARIO LABORAL (feriados o dias no laborables)
CREATE TABLE calendario_laboral(fec_calendario DATE PRIMARY KEY,
                                    tipo           VARCHAR(20) NOT NULL,
                                    descripcion    VARCHAR2(100)
)
----------------------------------------------------------------------------------------------------------------
--TABLA DE ASISTENCIAS
CREATE TABLE ASISTENCIA(id_asistencia     NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_usuario        NUMBER(10) NOT NULL                                    ,
                        fec_asistencia    DATE NOT NULL                                          ,
                        hora_entrada      TIMESTAMP NOT NULL                                     ,
                        hora_salida       TIMESTAMP                                              ,
                        estado_asistencia VARCHAR2(20) CHECK (estado_asistencia IN (
                                                                                    'PUNTUAL'     ,       
                                                                                    'TARDE'       ,         
                                                                                    'FALTA'       ,         
                                                                                    'JUSTIFICADA' ,   
                                                                                    'PERMISO'     ,       
                                                                                    'ENFERMEDAD'  )),
CONSTRAINT uk_asistencia_dia UNIQUE (id_usuario, fec_asistencia)  -- Restricción Única: Un usuario no puede tener dos registros la misma fecha
);
----------------------------------------------------------------------------------------------------------------
--




