/*============================================
PROYECTO: Sistema de control de asistencias
BD: Oracle
AUTOR: Luis Carbajal
FECHA: 06/12/2025
=============================================*/
--Tabla de Roles
CREATE TABLE ROL( id_rol NUMBER(2)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  nombre VARCHAR(25) NOT NULL UNIQUE 
);

COMMENT ON TABLE ROL IS 'Tabla maestra, que define los niveles de acceso y permiso dentro del sistema.';

--TABLA DE USUARIOS
CREATE TABLE USUARIO( id_usuario      NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                      username        VARCHAR(50)   NOT NULL UNIQUE                              ,
                      clave_hash      VARCHAR2(100) NOT NULL                                     ,
                      nombre_completo VARCHAR2(100) NOT NULL                                     ,
                      email           VARCHAR2(100)                                              ,
                      id_rol          NUMBER(2)     NOT NULL                                     ,
                      estado          NUMBER(1)     DEFAULT 1 NOT NULL CHECK(estado IN (0,1))    ,--1=Activo, 0=Inactivo
                      CONSTRAINT fk_user_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);
COMMENT ON TABLE USUARIO IS '1:Activo, 0:Inactivo';

--