/*============================================
PROYECTO: Sistema de control de asistencias
BD: Oracle
AUTOR: Luis Carbajal
FECHA: 06/12/2025
=============================================*/
--Tabla de Roles
CREATE TABLE ROL( id_rol NUMBER(2)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  nombre VARCHAR(25) NOT NULL UNIQUE 
);

COMMENT ON TABLE ROL IS 'Tabla maestra, que define los niveles de acceso y permiso dentro del sistema.';
------------------------------------------------------------------------------------------------------------------------------------------------------
--TABLA DE USUARIOS
CREATE TABLE USUARIO( id_usuario      NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                      username        VARCHAR(50)   NOT NULL UNIQUE                              ,
                      clave_hash      VARCHAR2(100) NOT NULL                                     ,
                      nombre_completo VARCHAR2(100) NOT NULL                                     ,
                      email           VARCHAR2(100)                                              ,
                      id_rol          NUMBER(2)     NOT NULL                                     ,
                      estado          NUMBER(1)     DEFAULT 1 NOT NULL CHECK(estado IN (0,1))    ,--1=Activo, 0=Inactivo
                      CONSTRAINT fk_user_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);
COMMENT ON TABLE USUARIO IS '1:Activo, 0:Inactivo';
------------------------------------------------------------------------------------------------------------------------------------------------------
--TABLA DE PARAMETROS
CREATE TABLE parametros(clave        VARCHAR(50) PRIMARY KEY,
                        valor        VARCHAR(100) NOT NULL,
                        descripcion  VARCHAR2(100)
);
COMMENT ON TABLE parametros IS 'Idea:hacer configuraciones dinamicas, por ej. tolerancia';
-----------------------------------------------------------------------------------------------------------------------------------------------------
--TABLA DE CALENDARIO LABORAL (feriados o dias no laborables)
CREATE TABLE calendario_laboral(fec_calendario DATE PRIMARY KEY,
                                    tipo           VARCHAR(20) NOT NULL,
                                    descripcion    VARCHAR2(100)
);
------------------------------------------------------------------------------------------------------------------------------------------------------
--TABLA DE ASISTENCIAS
CREATE TABLE ASISTENCIA(id_asistencia     NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_usuario        NUMBER(10) NOT NULL                                    ,
                        fec_asistencia    DATE NOT NULL                                          ,
                        hora_entrada      TIMESTAMP NOT NULL                                     ,
                        hora_salida       TIMESTAMP                                              ,
                        estado_asistencia VARCHAR2(20) CHECK (estado_asistencia IN (
                                                                                    'PUNTUAL'     ,       
                                                                                    'TARDE'       ,         
                                                                                    'FALTA'       ,         
                                                                                    'JUSTIFICADA' ,   
                                                                                    'PERMISO'     ,       
                                                                                    'ENFERMEDAD'  )),
CONSTRAINT uk_asistencia_dia UNIQUE (id_usuario, fec_asistencia)  -- Restricción Única: Un usuario no puede tener dos registros la misma fecha
);
-----------------------------------------------------------------------------------------------------------------------------------------------------
-- Creación de índices solicitados 
CREATE INDEX idx_asistencia_fecha ON asistencia(fec_asistencia);
CREATE INDEX idx_asistencia_user ON asistencia(id_usuario);
------------------------------------------------------------------------------------------------------------------------------------------------------
--Tabla de justificaciones(tardanzas o ausencias)
CREATE TABLE justificacion(id_justificacion NUMBER (10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY                                    ,
                           id_usuario       NUMBER (10)                                                                                 ,
                           fec_incidencia   DATE                                                                                        ,
                           motivo           CLOB NOT NULL                                                                               ,
                           estado_solicitud VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL CHECK(estado_solicitud IN ('PENDIENTE','APROBADO','RECHAZADO')),
                           fec_solicitud    TIMESTAMP DEFAULT SYSTIMESTAMP                                                              ,
                           CONSTRAINT fk_just_usr FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
                           
);
--------------------------------------------------------------------------------------------------------------------------------------------------------
--Tabla log_justificacion(AUDITORIA)
CREATE TABLE tbl_log_justificacion(
  id_log_just       NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY                   ,
  id_usuario        NUMBER(10)                                                                ,
  id_justificacion  NUMBER(10) NOT NULL                                                       ,
  fec_evento        TIMESTAMP  DEFAULT SYSTIMESTAMP                                           ,
  tipo_evento       VARCHAR2(20) NOT NULL CHECK (tipo_evento IN ('INSERT', 'UPDATE_ESTADO')),
  datos_antiguos    CLOB,
  datos_nuevos      CLOB,
  
  CONSTRAINT fk_log_just_usr FOREIGN KEY (id_usuario)       REFERENCES usuario (id_usuario),
  CONSTRAINT fk_log_just_id  FOREIGN KEY (id_justificacion) REFERENCES justificacion(id_justificacion)
);
---------------------------------------------------------------------------------------------------------------------------------------------------------
--Tabla log_asistencia(AUDITORIA)
CREATE TABLE tbl_log_asistencia(
  id_log_asistencia NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY                   ,
  id_usuario        NUMBER(10)                                                                ,
  id_asistencia     NUMBER(12) NOT NULL                                                       ,
  fec_evento        TIMESTAMP  DEFAULT SYSTIMESTAMP                                           ,
  tipo_evento       VARCHAR2(20) NOT NULL CHECK (tipo_evento IN ('INSERT', 'UPDATE','DELETE')),
  datos_antiguos    CLOB,
  datos_nuevos      CLOB,
  
  CONSTRAINT fk_log_asist_usr FOREIGN KEY (id_usuario)    REFERENCES usuario (id_usuario),
  CONSTRAINT fk_log_asist_id  FOREIGN KEY (id_asistencia) REFERENCES asistencia(id_asistencia)
);
---INSERTS INICIALES
INSERT INTO rol(nombre) VALUES ('ADMIN');
INSERT INTO rol(nombre) VALUES ('EMPLEADO');

INSERT INTO parametro(clave,valor,descripcion) VALUES ('Tolerancia_minutos','15','Minutos de tolerancia antes de considerar tardanza');
COMMIT;