--*******************************************
--CREACION DE USUARIO Y CONTRASEÑA 
--*******************************************
CREATE USER ASISTENCIA_SCHEMA IDENTIFIED BY  orcl23ai
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;
/*ALTER USER ASISTENCIA_SCHEMA
DEFAULT TABLESPACE users;
ALTER USER ASISTENCIA_SCHEMA
QUOTA UNLIMITED ON users;*/
--*******************************************
--CREACION DE PERMISOS --COMANDOS DCL
--*******************************************
GRANT CONNECT TO ASISTENCIA_SCHEMA;

GRANT RESOURCE TO ASISTENCIA_SCHEMA;

GRANT CREATE ANY VIEW TO ASISTENCIA_SCHEMA;
GRANT CREATE ANY PROCEDURE TO ASISTENCIA_SCHEMA;
GRANT CREATE ANY TRIGGER TO ASISTENCIA_SCHEMA;
GRANT CREATE ANY SEQUENCE TO ASISTENCIA_SCHEMA;

GRANT EXECUTE ON ANY PROCEDURE TO ASISTENCIA_SCHEMA;