###Varible
@authToken =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkluZHJhIiwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpYXQiOjE3NjU3NDU0MzUsImV4cCI6MTc2NTc1MjYzNX0.L8LYvzXkoREfRXs0jLssT27cDhhX2bYxqI441KXd4Hw

### Registrar Justificación (Exito)
POST http://localhost:8080/justificaciones/registrar
Authorization: {{authToken}}
Content-Type: application/json

{  
 "fechaIncidencia": "2025-12-25",
 "motivo": "Navidad, es feriado."
}

### LISTAR PENDIENTES (ADMIN)
GET http://localhost:8080/justificaciones/pendientes
Authorization: {{authToken}}

### APROBAR SOLICITUD (ADMIN) 
PATCH http://localhost:8080/justificaciones/2/atender
Authorization: {{authToken}}
Content-Type: application/json

{
  "estado": "APROBADO"
}

### 2. LISTAR INCIDENCIAS POR JUSTIFICAR
GET http://localhost:8080/justificaciones/incidencias
Authorization: {{authToken}}
Content-Type: application/json